### ISSUE TITLE
custom Github utils wrapper doesn't follow pagination

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k-ci#49]
https://github.com/cp2k/cp2k/pull/565 contains changes to `.py` files, yet the CI claims `Python — No related files were changed - skipping.`

**Comment by dev-zero** [comment]
btw,
https://github.com/cp2k/cp2k-ci/blob/5d102f3cb74933c3c57551fd49dfbaca4ecaead6/backend/backend.py#L294
... no need to get a full list, `any(..)` is happy with a generator

**Comment by dev-zero** [comment]
The reason is most likely in the Github wrapper not following `Links` for pagination.

```
$ curl -v https://api.github.com/repos/cp2k/cp2k/pulls/565/files > /dev/null
[...]
< Link: <https://api.github.com/repositories/151238791/pulls/565/files?page=2>; rel="next", <https://api.github.com/repositories/151238791/pulls/565/files?page=29>; rel="last"
[...]
```

... meaning we're hitting the limit of [300 files](https://developer.github.com/v3/pulls/#list-pull-requests-files) in this PR and one should follow the links for pagination.

**Comment by oschuett** [comment]
Fixed via https://github.com/cp2k/cp2k-ci/commit/392176e9d40b18e01399f55ecea749f2127e12c6. Thanks for reporting!
