### ISSUE TITLE
"Waiting for mergeability check" timeout when starting test for already merged PR

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k-ci#53]
I'm trying to pinpoint the failure in https://github.com/cp2k/cp2k/pull/482/checks?check_run_id=378881869 . Since I can't reproduce it locally, I would like to rerun checks on a previous PR here: https://github.com/cp2k/cp2k/runs/378943280

While I can `start` the test, it times out when "Waiting for mergeability check".

**Comment by oschuett** [comment]
This is an issue on Github's side. The mergeability check usually finishes within 5 seconds and I set the timeout generously at 50 seconds. Occasionally, Github does takes longer (about once every other week).

Today seems to be a particularly bad day as there were already two timeouts. I don't think increasing the timeout further will help. Instead people should just restart the check from the UI at a later time.
